'use strict';

import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_GLOBAL_INFO: null,
  REQUEST_GLOBAL_INFO_SUCCESS: null,
  REQUEST_GLOBAL_INFO_ERROR: null,

  FETCH_USER_INFORMATIONS: null,
  FETCH_USER_INFORMATIONS_SUCCESS: null,
  FETCH_USER_INFORMATIONS_ERROR: null,

  REQUEST_REGISTER_UNIV_EMAIL: null,
  REQUEST_REGISTER_UNIV_EMAIL_SUCCESS: null,
  REQUEST_REGISTER_UNIV_EMAIL_ERROR: null,

  REQUEST_PASSWORD_RENEW_MAIL: null,
  REQUEST_PASSWORD_RENEW_MAIL_SUCCESS: null,
  REQUEST_PASSWORD_RENEW_MAIL_ERROR: null,

  REQUEST_SEND_CONFIRM_MAIL: null,
  REQUEST_SEND_CONFIRM_MAIL_SUCCESS: null,
  REQUEST_SEND_CONFIRM_MAIL_ERROR: null,

  REQUEST_TOTAL_STATISTICS: null,
  REQUEST_TOTAL_STATISTICS_SUCCESS: null,
  REQUEST_TOTAL_STATISTICS_ERROR: null,

  REQUEST_MODAL_CONTENTS: null,
  REQUEST_MODAL_CONTENTS_SUCCESS: null,
  REQUEST_MODAL_CONTENTS_ERROR: null,

  REQUEST_SIGNIN_USER: null,
  REQUEST_SIGNIN_USER_SUCCESS: null,
  REQUEST_SIGNIN_USER_ERROR: null,

  REQUEST_SIGNUP_USER: null,
  REQUEST_SIGNUP_USER_SUCCESS: null,
  REQUEST_SIGNUP_USER_ERROR: null,

  REQUEST_SIGNOUT_USER: null,
  REQUEST_SIGNOUT_USER_SUCCESS: null,
  REQUEST_SIGNOUT_USER_ERROR: null,

  REQUEST_CHECK_DUPLICATES: null,
  REQUEST_CHECK_DUPLICATES_SUCCESS: null,
  REQUEST_CHECK_DUPLICATES_ERROR: null,

  REQUEST_UNIV_INFO: null,
  REQUEST_UNIV_INFO_SUCCESS: null,
  REQUEST_UNIV_INFO_ERROR: null,

  REQUEST_SINGLE_UNIV_INFO: null,
  REQUEST_SINGLE_UNIV_INFO_SUCCESS: null,
  REQUEST_SINGLE_UNIV_INFO_ERROR: null,

  REQUEST_MY_INFORMATIONS: null,
  REQUEST_MY_INFORMATIONS_SUCCESS: null,
  REQUEST_MY_INFORMATIONS_ERROR: null,

  REQUEST_MY_EVALUATIONS: null,
  REQUEST_MY_EVALUATIONS_SUCCESS: null,
  REQUEST_MY_EVALUATIONS_ERROR: null,

  REQUEST_CHECK_EVAL_POSSIBLE: null,
  REQUEST_CHECK_EVAL_POSSIBLE_SUCCESS: null,
  REQUEST_CHECK_EVAL_POSSIBLE_ERROR: null,

  REQUEST_MY_COMMENTS: null,
  REQUEST_MY_COMMENTS_SUCCESS: null,
  REQUEST_MY_COMMENTS_ERROR: null,

  CHANGE_MY_INFORMATIONS: null,
  CHANGE_MY_INFORMATIONS_SUCCESS: null,
  CHANGE_MY_INFORMATIONS_ERROR: null,

  CHANGE_MY_PASSWORD: null,
  CHANGE_MY_PASSWORD_SUCCESS: null,
  CHANGE_MY_PASSWORD_ERROR: null,

  REQUEST_RECENT_EVALUATION: null,
  REQUEST_RECENT_EVALUATION_SUCCESS: null,
  REQUEST_RECENT_EVALUATION_ERROR: null,

  REQUEST_COURSE_EVALUATIONS: null,
  REQUEST_COURSE_EVALUATIONS_SUCCESS: null,
  REQUEST_COURSE_EVALUATIONS_ERROR: null,

  REQUEST_SINGLE_EVALUATION: null,
  REQUEST_SINGLE_EVALUATION_SUCCESS: null,
  REQUEST_SINGLE_EVALUATION_ERROR: null,

  REQUEST_EVALUATION_WRITE: null,
  REQUEST_EVALUATION_WRITE_SUCCESS: null,
  REQUEST_EVALUATION_WRITE_ERROR: null,

  REQUEST_EVALUATION_UPDATE: null,
  REQUEST_EVALUATION_UPDATE_SUCCESS: null,
  REQUEST_EVALUATION_UPDATE_ERROR: null,

  REQUEST_EVALUATION_DELETE: null,
  REQUEST_EVALUATION_DELETE_SUCCESS: null,
  REQUEST_EVALUATION_DELETE_ERROR: null,

  REQUEST_REGISTER_HASHTAGS: null,
  REQUEST_REGISTER_HASHTAGS_SUCCESS: null,
  REQUEST_REGISTER_HASHTAGS_ERROR: null,

  REQUEST_RECOMMENDED_HASHTAGS: null,
  REQUEST_RECOMMENDED_HASHTAGS_SUCCESS: null,
  REQUEST_RECOMMENDED_HASHTAGS_ERROR: null,

  REQUEST_EVALUATION_VOTE: null,
  REQUEST_EVALUATION_VOTE_SUCCESS: null,
  REQUEST_EVALUATION_VOTE_ERROR: null,

  REQUEST_EVALUATION_VOTE_CANCEL: null,
  REQUEST_EVALUATION_VOTE_CANCEL_SUCCESS: null,
  REQUEST_EVALUATION_VOTE_CANCEL_ERROR: null,

  REQUEST_EVALUATION_VOTE_USERS: null,
  REQUEST_EVALUATION_VOTE_USERS_SUCCESS: null,
  REQUEST_EVALUATION_VOTE_USERS_ERROR: null,

  REQUEST_EVALUATION_REPORT: null,
  REQUEST_EVALUATION_REPORT_SUCCESS: null,
  REQUEST_EVALUATION_REPORT_ERROR: null,

  REQUEST_COURSE_DETAIL: null,
  REQUEST_COURSE_DETAIL_SUCCESS: null,
  REQUEST_COURSE_DETAIL_ERROR: null,

  REQUEST_COMMENTS_GET: null,
  REQUEST_COMMENTS_GET_SUCCESS: null,
  REQUEST_COMMENTS_GET_ERROR: null,

  REQUEST_COMMENT_WRITE: null,
  REQUEST_COMMENT_WRITE_SUCCESS: null,
  REQUEST_COMMENT_WRITE_ERROR: null,

  REQUEST_COMMENT_DELETE: null,
  REQUEST_COMMENT_DELETE_SUCCESS: null,
  REQUEST_COMMENT_DELETE_ERROR: null,

  REQUEST_COMMENT_VOTE: null,
  REQUEST_COMMENT_VOTE_SUCCESS: null,
  REQUEST_COMMENT_VOTE_ERROR: null,

  REQUEST_COMMENT_VOTE_CANCEL: null,
  REQUEST_COMMENT_VOTE_CANCEL_SUCCESS: null,
  REQUEST_COMMENT_VOTE_CANCEL_ERROR: null,

  REQUEST_COMMENT_VOTE_USERS: null,
  REQUEST_COMMENT_VOTE_USERS_SUCCESS: null,
  REQUEST_COMMENT_VOTE_USERS_ERROR: null,

  REQUEST_COMMENT_REPORT: null,
  REQUEST_COMMENT_REPORT_SUCCESS: null,
  REQUEST_COMMENT_REPORT_ERROR: null,

  REQUEST_SEARCH_COURSE: null,
  REQUEST_SEARCH_COURSE_SUCCESS: null,
  REQUEST_SEARCH_COURSE_ERROR: null,

  REQUEST_SEARCH_COURSE_FOR_EVAL: null,
  REQUEST_SEARCH_COURSE_FOR_EVAL_SUCCESS: null,
  REQUEST_SEARCH_COURSE_FOR_EVAL_ERROR: null,

  REQUEST_SET_FAVORITE_COURSE: null,
  REQUEST_SET_FAVORITE_COURSE_SUCCESS: null,
  REQUEST_SET_FAVORITE_COURSE_ERROR: null,

  REQUEST_FAVORITE_COURSE: null,
  REQUEST_FAVORITE_COURSE_SUCCESS: null,
  REQUEST_FAVORITE_COURSE_ERROR: null,

  CHECK_COURSE_VIEW_NEEDS_UPDATE: null,

  REQUEST_AUTO_COMPLETE: null,
  REQUEST_AUTO_COMPLETE_SUCCESS: null,
  REQUEST_AUTO_COMPLETE_ERROR: null,

  DROP_OUT: null,
  DROP_OUT_SUCCESS: null,
  DROP_OUT_ERROR: null
});
